title: 'Produkt Kategorien'
tabs:
  main:
    display: Hauptteil
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              localizable: true
              validate:
                - required
          -
            handle: content
            field:
              buttons:
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
                - h4
                - h5
                - h6
                - underline
                - strikethrough
                - small
                - superscript
                - subscript
                - horizontalrule
                - alignleft
                - aligncenter
                - alignright
                - alignjustify
              remove_empty_nodes: false
              type: bard
              display: Content
              localizable: true
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: order
            field:
              type: text
              display: Reihenfolge
              localizable: false
          -
            handle: slug
            field:
              type: slug
              required: true
              validate:
                - required
                - 'max:200'
              localizable: true
          -
            handle: websites_feld
            field:
              type: sites
              display: Websites
              localizable: false
