title: Allgemein
updated_by: 273e00a1-d447-4899-b66e-01da895d5a76
updated_at: 1734003620
blueprint: blogcategory
content:
  -
    type: paragraph
    attrs:
      textAlign: left
    content:
      -
        type: text
        text: 'Allgemeines rund um Thermoplan'
websites_feld:
  - de
