title: Produkte
tabs:
  main:
    display: Hauptteil
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              localizable: false
              validate:
                - required
              display: 'Titel des Eintrags'
              instructions: 'Wird in der Übersicht angezeigt'
          -
            handle: product_categories
            field:
              type: terms
              taxonomies:
                - product_categories
              display: 'Produkt Kategorie'
              mode: select
              localizable: false
              max_items: 1
              validate:
                - required
          -
            handle: product_icon
            field:
              max_files: 1
              container: assets
              type: assets
              display: 'Produkt Icon'
              localizable: false
          -
            import: text_component
          -
            import: imageelement
          -
            import: videoelement
      -
        display: Inhalte
        fields:
          -
            import: weitere_inhalte
  seo:
    display: SEO
    sections:
      -
        display: SEO
        fields:
          -
            import: seodata
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: author
            field:
              type: users
              display: Author
              default: current
              localizable: true
              max_items: 1
          -
            handle: parent
            field:
              type: entries
              collections:
                - products
              max_items: 1
              listable: false
              localizable: true
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
          -
            handle: show_references
            field:
              default: true
              type: toggle
              display: 'Logos im Footer'
              instructions: 'Zeigt den Logoslider im Fussbereich der Seite an.'
              localizable: false
