title: Produkte
sites:
  - de
  - en
propagate: false
template: products/show
layout: layout
taxonomies:
  - product_categories
revisions: false
route: 'products/{slug}/'
sort_dir: desc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: false
